name: 'Reusable: Code Style Review'

on:
  workflow_call:

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1

      - name: 'Set up Reviewdog'
        env:
          REVIEWDOG_INSTALLER: 'https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh'
        run: |
          mkdir -p $HOME/bin
          curl -sfL ${REVIEWDOG_INSTALLER} | sh -s -- -b $HOME/bin

      - name: 'Set up Rubocop'
        run: 'gem install rubocop rubocop-minitest rubocop-performance rubocop-rails'

      - name: 'Run Rubocop'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rubocop |
          $HOME/bin/reviewdog \
          -f=rubocop \
          -name="Rubocop" \
          -reporter=github-pr-review \
          -level=error \
          -diff="git diff $DIFF_BRANCH"
