
name: 'Reusable: Build and push image'

on:
  workflow_call:
    secrets:
      PUZZLE_REGISTRY_USERNAME:
        description: 'Needed for the registry login'
        required: false
      PUZZLE_REGISTRY_TOKEN:
        description: 'Needed for the registry login'
        required: false
      PUZZLE_DEP_TRACK_URL:
        description: 'Needed for the dependency track push'
        required: false
      PUZZLE_DEP_TRACK_TOKEN:
        description: 'Needed for the dependency track push'
        required: false

env:
  DECIDIM_IMAGE_REPO: 'registry.puzzle.ch/decidim/stbi-rails'

jobs:
  build:
    environment: deploy
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to the puzzle registry
        uses: docker/login-action@v1
        with:
          registry: registry.puzzle.ch
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ env.DECIDIM_IMAGE_REPO }}:latest
